version: '3'
services:
  # Airflow в отдельном контейнере
  airflow:
    # Сборка из Dockerfile
    build: .
    restart: always
    ports:
      - 8001:8080
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/root/airflow/plugins
      - logs:/usr/local/airflow/logs
    depends_on:
      - postgres

  # PostgreSQL
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ibbvs
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: default
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Маппинг для сохранения данных

  # ClickHouse
  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - 8123:8123
      - 9000:9000

volumes:
  logs:
  postgres_data:  # Добавленный volume для сохранения данных PostgreSQL
